# This is a template for the configuration file.
# Copy this file to config.yml and edit the paths to your databases.

# configuration file
PHAGES_DIR: test/data
OUTPUT_DIR: test/output
INPUT_EXTENSION: fasta
PHAGE_MIN_LENGTH: 2000 # bp
GLIMMER_TRAIN: /path/to/your/databases/training-file_refseq.icm
SEARCH_TOOL: hhsearch # hhblits (faster) | hhsearch (more sensitive)

# proteins families
CLUSTERING:
  IDENTITY: 0.5
  COVERAGE: 0.8
  EVAL: 0.001
  SENSITIVITY: 7.5

# paths to HHsuite databases
HHSUITE:
  PHROGS: /path/to/your/databases/phrogs_hhsuite_db/phrogs
  PFAM: /path/to/your/databases/pfamA_32/pfam
  ECOD: /path/to/your/databases/ECOD_F70/ECOD_F70_20200207
  ALANDB: /path/to/your/databases/AlanDavidson/profile-db/all_proteins

# paths to metadata tables
METADATA:
  PHROGS_TABLE: 'dependencies/tables/phrog_annot_v4.tsv'
  MGG_PHROGS_TABLE: 'dependencies/tables/v3_phrogs-table-rafal-3_12.csv'
  ALAN_TABLE: 'dependencies/tables/alan_annot.tsv'
