name: phage_annotation
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3.11
  - biopython=1.79
  - pandas=3.0.2
  - numpy=2.4.4
  - seaborn
  - matplotlib=3.10.8
  - hhsuite=3.3.0
  - mmseqs2=16.747c6
  - clustalo=1.2.4
  - bedtools=2.30.0
  - glimmer=3.02
  - prodigal-gv=2.11.0
  - ffindex=0.98
  - pip
  - pip:
      - csb==1.2.5